[package]
name = "helpet_unlock"
version = "0.1.0"
authors = ["Tu Nombre <tu_email@dominio.com>"]
edition = "2018"

[dependencies]
solana-program = { version = "1.18", features = ["full"] }
spl-token = { version = "3.3.0" }
